build: add dependency on gio-unix
When trying to build the package on NixOS, it fails with

```
xdp-dbus.c:16:12: fatal error: gio/gunixfdlist.h: No such file or directory
 #  include <gio/gunixfdlist.h>
            ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

`gio-unix-2.0` dependency needs to be listed explicitly.